language: ruby
rvm: 2.1
services:
  - redis-server
before_script:
  - cp config/database.yml.postgres config/database.yml
  - cp config/justask.yml.example config/justask.yml
  - bundle exec rake db:drop db:create db:migrate db:test:prepare
