language: ruby
rvm: 2.0.0
before_script:
  - cp config/database.yml.postgres config/database.yml
  - cp config/justask.yml.example config/justask.yml
  - bundle exec rake db:setup
  - bundle exec rake db:migrate
